{{- if .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "microservice-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservice-chart.labels" . | nindent 4 }}
spec:
  host: {{ include "microservice-chart.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local
  trafficPolicy:
    {{- toYaml .Values.istio.destinationRule.trafficPolicy | nindent 4 }}
{{- end }}
